// List of supported networks with corresponding block explorer links
export const networksInfo = {
  localhost: "N/A",
  hardhat: "N/A",
  sepolia: "https://sepolia.etherscan.io/",
  holesky: "https://holesky.etherscan.io/",
  bscTestnet: "https://testnet.bscscan.com/",
  optimismSepolia: "https://sepolia-optimism.etherscan.io/",
  arbitrumSepolia: "https://sepolia.arbiscan.io/",
  amoy: "https://amoy.polygonscan.com/",
  polygonZkEVMTestnet: "https://cardona-zkevm.polygonscan.com/",
  fantomTestnet: "https://testnet.ftmscan.com/",
  fuji: "https://testnet.snowtrace.io/",
  chiado: "https://gnosis-chiado.blockscout.com/",
  moonbaseAlpha: "https://moonbase.moonscan.io/",
  alfajores: "https://alfajores.celoscan.io/",
  auroraTestnet: "https://explorer.testnet.aurora.dev/",
  harmonyTestnet: "https://explorer.testnet.harmony.one/",
  spark: "https://explorer.fusespark.io/",
  cronosTestnet: "https://cronos.org/explorer/testnet3/",
  evmosTestnet: "https://www.mintscan.io/evmos-testnet/",
  bobaTestnet: "https://testnet.bobascan.com/",
  cantoTestnet: "https://testnet.tuber.build/",
  baseSepolia: "https://sepolia.basescan.org/",
  mantleTestnet: "https://sepolia.mantlescan.xyz/",
  filecoinTestnet: "https://calibration.filfox.info/en/",
  scrollSepolia: "https://sepolia.scrollscan.com/",
  lineaTestnet: "https://sepolia.lineascan.build/",
  zoraSepolia: "https://sepolia.explorer.zora.energy/",
  luksoTestnet: "https://explorer.execution.testnet.lukso.network/",
  mantaTestnet: "https://pacific-explorer.sepolia-testnet.manta.network/",
  blastTestnet: "https://sepolia.blastscan.io/",
  dosTestnet: "https://test.doscan.io/",
  fraxtalTestnet: "https://holesky.fraxscan.com/",
  metisTestnet: "https://sepolia-explorer.metisdevops.link/",
  modeTestnet: "https://sepolia.explorer.mode.network/",
  seiArcticTestnet: "https://seistream.app/",
  xlayerTestnet: "https://www.oklink.com/xlayer-test/",
  bobTestnet: "https://testnet-explorer.gobob.xyz/",
  coreTestnet: "https://scan.test.btcs.network/",
  telosTestnet: "https://testnet.teloscan.io/",
  rootstockTestnet: "https://rootstock-testnet.blockscout.com/",
  chilizTestnet: "https://testnet.chiliscan.com/",
  taraxaTestnet: "https://testnet.explorer.taraxa.io/",
  taikoTestnet: "https://hekla.taikoscan.io/",
  zetaChainTestnet: "https://athens.explorer.zetachain.com/",
  "5ireChainTestnet": "https://testnet.5irescan.io/",
  ethMain: "https://etherscan.io/",
  bscMain: "https://bscscan.com/",
  optimismMain: "https://optimistic.etherscan.io/",
  arbitrumOne: "https://arbiscan.io/",
  arbitrumNova: "https://nova.arbiscan.io/",
  polygon: "https://polygonscan.com/",
  polygonZkEVMMain: "https://zkevm.polygonscan.com/",
  fantomMain: "https://ftmscan.com/",
  avalanche: "https://snowtrace.io/",
  gnosis: "https://gnosisscan.io/",
  moonriver: "https://moonriver.moonscan.io/",
  moonbeam: "https://moonbeam.moonscan.io/",
  celo: "https://celoscan.io/",
  auroraMain: "https://explorer.mainnet.aurora.dev/",
  harmonyMain: "https://explorer.harmony.one/",
  fuse: "https://explorer.fuse.io/",
  cronosMain: "https://cronoscan.com/",
  evmosMain: "https://www.mintscan.io/evmos/",
  bobaMain: "https://bobascan.com/",
  cantoMain: "https://tuber.build/",
  baseMain: "https://basescan.org/",
  mantleMain: "https://mantlescan.xyz/",
  filecoinMain: "https://filfox.info/en/",
  scrollMain: "https://scrollscan.com/",
  lineaMain: "https://lineascan.build/",
  zoraMain: "https://explorer.zora.energy/",
  luksoMain: "https://explorer.execution.mainnet.lukso.network/",
  mantaMain: "https://pacific-explorer.manta.network/",
  blastMain: "https://blastscan.io/",
  dosMain: "https://doscan.io/",
  fraxtalMain: "https://fraxscan.com/",
  enduranceMain: "https://explorer-endurance.fusionist.io/",
  kavaMain: "https://kavascan.com/",
  metisMain: "https://andromeda-explorer.metis.io/",
  modeMain: "https://explorer.mode.network/",
  xlayerMain: "https://www.oklink.com/xlayer/",
  bobMain: "https://explorer.gobob.xyz/",
  coreMain: "https://scan.coredao.org/",
  telosMain: "https://www.teloscan.io/",
  rootstockMain: "https://rootstock.blockscout.com/",
  chilizMain: "https://chiliscan.com/",
  taraxaMain: "https://mainnet.explorer.taraxa.io/",
  gravityAlphaMain: "https://explorer.gravity.xyz/",
  taikoMain: "https://taikoscan.io/",
  zetaChainMain: "https://explorer.zetachain.com/",
  "5ireChainMain": "https://5irescan.io/",
} as const;

// Define a type `SupportedNetwork` that represents the union of all possible network names
// from the `networksInfo` object. This type ensures that any value assigned to a variable
// of type `SupportedNetwork` is a valid network key in `networksInfo`. It provides
// compile-time safety by preventing the use of unsupported or misspelled network names,
// allowing us to catch potential errors early and ensure consistency when working with
// network-specific functions or data
export type SupportedNetwork = keyof typeof networksInfo;
export const networks = Object.keys(networksInfo);
export const explorers = Object.values(networksInfo);

// Generate the transaction hash link
export const getTxHashLink = (network: SupportedNetwork, hash: string) =>
  `${networksInfo[network]}${network.startsWith("filecoin") ? "message" : network === "seiArcticTestnet" ? "transactions" : "tx"}/${hash}`;

// Generate the contract address link
export const getAddressLink = (network: SupportedNetwork, address: string) =>
  `${networksInfo[network]}${network === "seiArcticTestnet" ? "account" : "address"}/${address}`;
