name: 👮‍♂️ Sanity checks

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  prettify-n-lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]

      - name: Prettier and lint
        run: pnpm lint:check

  codespell:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2.0
        with:
          check_filenames: true
          skip: ./.git,pnpm-lock.yaml
          ignore_words_list: superseed

  validate-links:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby_version:
          - 4.0

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Install awesome_bot
        run: gem install awesome_bot -v 1.20.0

      - name: Validate URLs
        run: |
          awesome_bot ./*.md src/*.ts src/**/*.ts --allow-dupe --request-delay 0.4 \
          --white-list http://127.0.0.1:8545,https://github.com/pcaversaccio/createx,https://rpc.sepolia.org,https://0xrpc.io/hoodi,https://www.oklink.com,https://5irescan.io,https://testnet.5irescan.io
